tmux-session-name: gmw-smp
server-directory: ../testing-server
mc-version: 1.16.1
paper-build: latest
server-repo: git@github.com:GMW-SMP/server.git
packages-repo: git@github.com:GMW-SMP/packages.git
