#!/bin/bash

# Debugging
# set -x

OLD_DIR=$(pwd)
BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
cd $BASE_DIR

if [[ $1 == "start" ]]; then
  shift
  sh ./scripts/start.sh $@
elif [[ $1 == "backup" ]]; then
  shift
  sh ./scripts/backup.sh $@
elif [[ $1 == "stop" ]]; then
  shift
  sh ./scripts/stop.sh $@
elif [[ $1 == "update-paper" ]]; then
  shift
  sh ./scripts/update-paper.sh $@
elif [[ $1 == "update-server" ]]; then
  shift
  sh ./scripts/update-server.sh $@
elif [[ $1 == "update-management" ]]; then
  shift
  sh ./scripts/update-management.sh $@
fi

cd $OLD_DIR
