#!/bin/bash

# Do not change this file if possible.
# if it must be changed then updating through the update-manage.sh file
# will probably make bad things happen.

mkdir ./tmp
cp -r ./scripts/ ./tmp

bash ./tmp/manage.sh $@

rm -rf ./tmp
